name: Test and Deploy

on:
  pull_request:
  push:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.8
      - name: Run bundle install
        run: |
          bundle config --local path vendor/bundle
          bundle config --local without production
      - run: RAILS_ENV=test bundle exec rails assets:precompile
      - run: bundle exec rails test
